# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stubs/shop.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='stubs/shop.proto',
  package='shop',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10stubs/shop.proto\x12\x04shop\"F\n\x04Shop\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0bretailer_id\x18\x03 \x01(\x05\x12\x0f\n\x07\x61\x64\x64ress\x18\x04 \x01(\t\",\n\x10ShopListResponse\x12\x18\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\n.shop.Shop\"\"\n\x0bShopRequest\x12\x13\n\x0bretailer_id\x18\x01 \x01(\x05\x32I\n\x0bShopService\x12:\n\x0bGetShopList\x12\x11.shop.ShopRequest\x1a\x16.shop.ShopListResponse\"\x00\x62\x06proto3'
)




_SHOP = _descriptor.Descriptor(
  name='Shop',
  full_name='shop.Shop',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='shop.Shop.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='shop.Shop.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='retailer_id', full_name='shop.Shop.retailer_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='address', full_name='shop.Shop.address', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=96,
)


_SHOPLISTRESPONSE = _descriptor.Descriptor(
  name='ShopListResponse',
  full_name='shop.ShopListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='shop.ShopListResponse.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=142,
)


_SHOPREQUEST = _descriptor.Descriptor(
  name='ShopRequest',
  full_name='shop.ShopRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='retailer_id', full_name='shop.ShopRequest.retailer_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=178,
)

_SHOPLISTRESPONSE.fields_by_name['data'].message_type = _SHOP
DESCRIPTOR.message_types_by_name['Shop'] = _SHOP
DESCRIPTOR.message_types_by_name['ShopListResponse'] = _SHOPLISTRESPONSE
DESCRIPTOR.message_types_by_name['ShopRequest'] = _SHOPREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Shop = _reflection.GeneratedProtocolMessageType('Shop', (_message.Message,), {
  'DESCRIPTOR' : _SHOP,
  '__module__' : 'stubs.shop_pb2'
  # @@protoc_insertion_point(class_scope:shop.Shop)
  })
_sym_db.RegisterMessage(Shop)

ShopListResponse = _reflection.GeneratedProtocolMessageType('ShopListResponse', (_message.Message,), {
  'DESCRIPTOR' : _SHOPLISTRESPONSE,
  '__module__' : 'stubs.shop_pb2'
  # @@protoc_insertion_point(class_scope:shop.ShopListResponse)
  })
_sym_db.RegisterMessage(ShopListResponse)

ShopRequest = _reflection.GeneratedProtocolMessageType('ShopRequest', (_message.Message,), {
  'DESCRIPTOR' : _SHOPREQUEST,
  '__module__' : 'stubs.shop_pb2'
  # @@protoc_insertion_point(class_scope:shop.ShopRequest)
  })
_sym_db.RegisterMessage(ShopRequest)



_SHOPSERVICE = _descriptor.ServiceDescriptor(
  name='ShopService',
  full_name='shop.ShopService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=180,
  serialized_end=253,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetShopList',
    full_name='shop.ShopService.GetShopList',
    index=0,
    containing_service=None,
    input_type=_SHOPREQUEST,
    output_type=_SHOPLISTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SHOPSERVICE)

DESCRIPTOR.services_by_name['ShopService'] = _SHOPSERVICE

# @@protoc_insertion_point(module_scope)
